version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - cd viewer-test
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls
artifacts:
  files:
    - 'viewer-test/build/**/*'
