name: delete merged branch

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - name: Delete merged branch
      uses: SvanBoxel/delete-merged-branch@v1.3.3
